---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_omnibus: false
  require_chef_for_busser: false
  require_ruby_for_busser: true
  requirements_path: requirements.txt

platforms:
  - name: ubuntu-14.04

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'
