---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_omnibus: false
  requirements_path: requirements.txt
  require_chef_for_busser: false
  require_ruby_for_busser: true

platforms:
  - name: ubuntu-14.04
    driver_plugin: vagrant
    driver_config:
      box: ubuntu/trusty64

suites:
  - name: default

verifier:
  ruby_bindir: '/usr/bin'
