---
sudo: required
dist: trusty
language: generic

install:
  - sudo apt-get update -q
  - sudo apt-get install ruby
  - gem install test-kitchen
  - sudo apt-get install virtualbox
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - bundle install

script:
  - kitchen test
